#' Write a parameter file
#'
#' Writes a list of parameters to a file
#'
#' This function creates a parameter file that can be read by 
#' \code{\link{run_sim_P}}. It should be used in conjection with 
#' \code{\link{make_parmlist}}.
#'
#' @param parm_list (required) list of parameters, as generated by 
#' 	\code{\link{make_parmlist}}
#' @param f (required) file path
#' @return nothing
#'
#' export
write_parms = function(parm_list, f){

	make_newline = function(varname, value){
		if(length(value)==1){
			if(is.numeric(value)) new_line = paste(varname, value, sep='=')
			if(is.character(value)) new_line = paste0(varname, "='", value, "'")
			if(is.logical(value)) new_line = paste(varname, value, sep='=')
		} else {
			if(is.numeric(value)) new_line = paste0(varname, '=c(', paste(value, collapse=','), ')')
			if(is.character(value)) new_line = paste0(varname, '=c(', paste0("'", value, "'", collapse=','), ')')
		}
		new_line
	}

	this_file = file(f, open='w')
	for(i in 1:length(parm_list)){
		varname = names(parm_list)[i]
		value = parm_list[[i]]
	
		if(class(value)=='function'){
			new_line = c(paste0(varname,'='), deparse(value))	
		} else {	

		if(class(value)=='list'){
			line_list = paste(sapply(1:length(value), function(j){
				subvalue = value[[j]]
				make_newline(names(value)[j], subvalue)
			}), collapse=',')
			new_line = paste0(varname, '=list(', line_list, ')')
		} else {
			new_line = make_newline(varname, value)
		}}
				
		writeLines(new_line, this_file)
	}
	close(this_file)	
}